import json
import glob
import os
from datetime import datetime

# --- CONFIGURATION ---
TARGET_NAME = "LogiFlow Technologies"  # <--- CHANGE THIS FOR EACH CLIENT
# ---------------------

def generate_final_report():
    # 1. Find the latest context file (The Final State)
    files = glob.glob("storage/contexts/*.json")
    files.sort()
    
    if not files:
        print("❌ No data found.")
        return

    last_file = files[-1]
    with open(last_file, "r") as f:
        data = json.load(f)

    # 2. Extract the Master Register
    master_register = data.get("cumulative_risk_register", [])
    
    if not master_register:
        print("❌ No risks found in the Master Register.")
        return

    # 3. Generate Markdown Content
    report = f"""# CONFIDENTIAL DUE DILIGENCE MEMORANDUM
**Target:** {TARGET_NAME}
**Date:** {datetime.now().strftime('%Y-%m-%d')}
**Generated By:** GAP Autonomous Engine
**Source Documents:** {len(files)-1} files analyzed

## EXECUTIVE SUMMARY
The autonomous review of the provided data room has identified **{len(master_register)} material risks**. 
The following report details specific findings with citations to the source documents.

---

## DETAILED RISK REGISTER

"""
    
    # Group by Severity
    high_risks = [r for r in master_register if r['severity'] == 'HIGH']
    med_risks = [r for r in master_register if r['severity'] == 'MEDIUM']
    low_risks = [r for r in master_register if r['severity'] == 'LOW']

    def add_section(title, risks, icon):
        section = f"### {icon} {title} ({len(risks)})\n"
        for i, r in enumerate(risks, 1):
            section += f"**{i}. {r['category']}**\n"
            section += f"{r['description']}\n\n"
            # Handle evidence list
            if r['evidence']:
                for ev in r['evidence']:
                    section += f"> *\"{ev['verbatim_quote']}\"*\n"
                    section += f"> *(Source: {ev['document_name']}, Pg {ev['page_number']})*\n\n"
            else:
                section += "> *No specific citation provided.*\n\n"
        return section

    if high_risks:
        report += add_section("CRITICAL RISKS (Deal Breakers)", high_risks, "🔴")
    
    if med_risks:
        report += add_section("MATERIAL RISKS (Negotiation Points)", med_risks, "🟡")

    if low_risks:
        report += add_section("MINOR RISKS", low_risks, "🟢")

    # 4. Save to File (UTF-8 Enforced)
    with open("FINAL_REPORT.md", "w", encoding="utf-8") as f:
        f.write(report)
    
    print(f"✅ Report Generated: FINAL_REPORT.md ({len(master_register)} risks aggregated)")

if __name__ == "__main__":
    generate_final_report()